### ISSUE TITLE
Timeliness 0.3.7 fails when using strict formats "d mmmm yyyy" & "dd mmmm yyyy"

### ISSUE THREAD

**Issue by edwinmeyer** [adzap/timeliness#16]
Timeliness 0.3.7 fails when using strict formats "d mmmm yyyy" & "dd mmmm yyyy", e.g.
  Timeliness.parse("1 Jan 2012", :format => "d mmmm yyyy")
  SyntaxError: (eval):1: duplicated argument name
  def process(day,month,month,year)
    from bundle/ruby/1.9.1/gems/timeliness-0.3.7/lib/timeliness/format.rb:62:in `instance_eval'

**Comment by adzap** [comment]
There is not 'mmmm' format token defined. Perhaps that is the problem. Did you mean mmm?
