### ISSUE TITLE
parse fails when validates_timeliness is included

### ISSUE THREAD

**Issue by zeeMonkeez** [adzap/timeliness#20]
I use rails 4.2.1, timeliness is at 0.3.8, and validates_timeliness is at 4.0.2.
In `rails console`, `Timeliness.parse('3 Jun 2016')` returns `nil` if validates_timeliness is in my Gemfile, and a correct `Time` if not (or when required from `irb`). `Timeliness._parse('3 Jun 2016')` returns a correct array in either case. In plain ruby (from irb), validates_timeliness does not seem to have an effect on parsing.
Not quite sure how to debug.

**Comment by adzap** [comment]
I know this is an old issue, sorry about that. So `timeliness` and `validates_timeliness` are not the same. But if you are using `timeliness` in the rails console it will be affected by the settings you have for `validates_timeliness`. Your example returns a valid Time object in the latest version of Timeliness.

Again sorry for the late reply, hope you figured it out.
