### ISSUE TITLE
Output Format - Doc Clarity Issue

### ISSUE THREAD

**Issue by dmc2015** [adzap/timeliness#24]
This looks like a great gem. I am trying to understand the documentation though.

Per the doc:
```
Timeliness.parse('2010-09-08 12:13:14') #=> Wed Sep 08 12:13:14 1000 2010
```
What actually happens:
```
Timeliness.parse('2010-09-08 12:13:14') #=> 2010-09-08 12:13:14 -0400
```

It would appear that the format option is for understanding the input, not formatting the output.

Is there a way to do this? I would like to provide an input and then get an output of the specified format like this:
```
Timeliness.parse('2010-09-08 12:13:14', :format => "yyyy/dd/mm hh:nn:ss") #=> 2010/08/09 12:13:14
```

**Comment by adzap** [comment]
Thanks for your interest.
This gem has no facility to output to string formats. It only parses strings into Time objects. The format option limits what format the input string should be considered valid.
I had always wanted to add an output function using the customisable format tokens the gem allows. Alas I never got there.
On Sat, May 13, 2017 at 11:40 AM, don mclamb <notifications@github.com> wrote:
This looks like a great gem. I am trying to understand the documentation though.

Per the doc:

ruby
Timeliness.parse('2010-09-08 12:13:14') #=> Wed Sep 08 12:13:14 1000 2010


What actually happens:

ruby
Timeliness.parse('2010-09-08 12:13:14') #=> 2010-09-08 12:13:14 -0400


It would appear that the format option is for understanding the input, not formatting the output.

Is there a way to do this? I would like to provide an input and then get an output of the specified format like this:

ruby
Timeliness.parse('2010-09-08 12:13:14', :format => "yyyy/dd/mm hh:nn:ss") #=> 2010/08/09 12:13:14
