### ISSUE TITLE
Timeliness 0.3.9 has invalid file permissions

### ISSUE THREAD

**Issue by tanelsuurhans** [adzap/timeliness#30]
When installing the latest version of the gem, the main file included comes with invalid permissions, preventing anyone but the owner from reading/executing the file.

This breaks production deployments where the application is ran as a separate user from the deploy user (i.e shared groups).

```
​$ ls -la /Users/tanel/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/timeliness-0.3.9/lib
total 8
drwxr-xr-x   4 tanel.suurhans  staff   128B Feb  4 11:04 ./
drwxr-xr-x  11 tanel.suurhans  staff   352B Feb  5 12:13 ../
drwxr-xr-x  10 tanel.suurhans  staff   320B Feb  4 11:04 timeliness/
-rw-------   1 tanel.suurhans  staff   1.1K Feb  4 11:04 timeliness.rb
```

**Comment by macfanatic** [comment]
Broke production for us just now as well, without failing any changes on CI or local development.  Not a great find for a patch minor release.

**Comment by adzap** [comment]
That sucks, sorry about. Don' know how that happened. Seems some of my old projects file permissions might be borked. Need to review them all.

I have pushed 0.3.10 and yanked 0.3.9. Let me know if that is all good.

**Comment by rodovich** [comment]
I encountered the problem with 0.3.9 and can confirm that it works under 0.3.10.

**Comment by adzap** [comment]
thanks!

**Comment by tanelsuurhans** [comment]
Thank you for taking care of this so quickly. The new release solved the problem.
