### ISSUE TITLE
Timeliness broken in multithreaded environments by default

### ISSUE THREAD

**Issue by fsateler** [adzap/timeliness#33]
Pull request #27 added a thread-local storage for the compiled formats. However, it does not copy the default values over when a new thread is started. This means that multithreaded environments (such as puma) are broken by default.

Reproducer code:

```ruby
require 'timeliness'
thread = Thread.new { sleep(0.005); Timeliness.parse '2019-01-01', format: 'yyyy-mm-dd' }
thread.join
puts thread.value # prints nil
```

(BTW, why do I need the default format sets when I'm passing an explicit format?)

cc @timdiggins

**Comment by adzap** [comment]
Thanks for the bug report. I have pushed a fix for this, as it should be using the current parent values in any new thread. I have also simplified the whole threadsafe approach to using a single 'current_date_format' accessor.

The remaining issue with my approach is that there is no way to change to parent thread default ambiguous date format that would be used in any new thread. Basically it would ignore if you had changed from US to Euro in a new thread and just use the US until you explicitly changed it in the new thread. I have a solution (not pushed) but it will be to add new top level config.

PS. Fair point about an explicit format needing a format set to work. Will look into that.

**Comment by adzap** [comment]
Added the config `ambiguous_date_format` for setting main thread default.

P.S. the reason you need a format set to parse with an explicit format is to possibly avoid compiling an existing format, which would be slower. It is advised to `add_format` any explicit formats you would use in the parse method to avoid the compilation hit each time.

**Comment by timdiggins** [comment]
@adzap I feel like the ability to change the default ambiguous_date_format could be (should be?) immutable (once set). It's a config (it's a global...) -- keeping it mutable just feels like lots of pain. And I can't see a convincing use case for mutability.

Also, I presume that the format compiling is **really** expensive? (cause otherwise wouldn't it be better to lazily compile them per thread (store them in threadlocals by format_name when compiled?), or even not to compile them at all).

sorry if i'm saying very obvious and stupid things -- just in case the outside perspective is helpful.

**Comment by fsateler** [comment]
Thanks for the quick fix! I will verify with the codebase at work on monday.

**Comment by fsateler** [comment]
I have done a quick verification with local project. It looks working to me.

Thanks again for fixing this so fast, and thanks for maintaining this awesome gem.

**Comment by adzap** [comment]
@timdiggins not sure how to enforce immutability while allowing it to be configured in various contexts. The gem is not only used in Rails to we need to allow for it's use in any context where there may not be a natural initialisation process as per Rails. To achieve optional immutability, say in Rails, the config on the Timeliness module could be moved into a config object that could be frozen at will e.g. during Rails initialization.

Re compilation, it is expensive enough to avoid doing it in any threaded context, again remembering we don't know how the gem might be used. In previous Rubies the kind of dynamic method compilation that happens would caused a flush of the global method cache. That method caching invalidation logic has been greatly improved in later Rubies being far more localised. But even so I don't fell it is necessary to recompile a static format set again and again.

Compiling these formats gave a speed boost which was significant in past Rubies. I have looked into perf for a while.
