### ISSUE TITLE
High memory, without any usage at all

### ISSUE THREAD

**Issue by envygeeks** [adzap/timeliness#34]
Your gem boots using 259MB of memory, just by loading: 
2592812  timeliness-0.4.0

**Comment by envygeeks** [comment]
```
2459926  vendor/bundle/ruby/2.5.0/gems/timeliness-0.4.0/lib/timeliness/format.rb
```

**Comment by envygeeks** [comment]
```
1774034  vendor/bundle/ruby/2.5.0/gems/timeliness-0.4.0/lib/timeliness/format.rb:22
```

**Comment by adzap** [comment]
I presume you are using the`memory_profiler` gem, which means I think you've interpreted the output wrong. I think that is 2.59MB.

You can add `scale_bytes: true` to convert output to units.
