### ISSUE TITLE
Facing a syntax error in format.rb in version 0.4.4

### ISSUE THREAD

**Issue by waqar-haider-confiz** [adzap/timeliness#40]
Hello,

My code is breaking with a syntax error at following line. It was not in previous version. 
Error message:

> /timeliness-0.4.4/lib/timeliness/format.rb:68: syntax error, unexpected [, expecting ')'

Can you please check?
https://github.com/adzap/timeliness/blob/2b7265842a0423c836a8723b3e664bac2dc49a00/lib/timeliness/format.rb#L68

**Comment by adzap** [comment]
What Ruby version?

Do you know which format is causing this by chance?

If it's possible, can add the line `puts @format_string` above the `instance_eval` call in this method it would be helpful to see which one it is.

**Comment by waqar-haider-confiz** [comment]
I am using **ruby 2.0.0p648 (2015-12-16) [x86_64-linux]**

I am facing the error when I require ms_rest (0.6.4) gem

`require 'ms_rest'`


Thanks

**Comment by waqar-haider-confiz** [comment]
I checked for syntax issue online, can also be seen in following screenshot
![SyntaxIssue](https://user-images.githubusercontent.com/10165814/73067266-08318380-3eca-11ea-93c8-a87dc68ddc5e.png)

**Comment by adzap** [comment]
Ah Ruby 2.0 is no longer officially supported. 

The syntax checker seems to be tripped up by this method doing an  `instance_eval` on a string.

Can you paste the full backtrace for the error?

**Comment by waqar-haider-confiz** [comment]
```
haider@haider-3347:~$ gem install timeliness
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
Successfully installed timeliness-0.4.4
Parsing documentation for timeliness-0.4.4
Installing ri documentation for timeliness-0.4.4
1 gem installed
haider@haider-3347:~$ irb
2.0.0-p648 :001 > require 'ms_rest'
SyntaxError: /home/haider/.rvm/gems/ruby-2.0.0-p648/gems/timeliness-0.4.4/lib/timeliness/format.rb:68: syntax error, unexpected [, expecting ')'
        [#{values.map { |i| i || 'nil' }.join(',')}]
         ^
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/haider/.rvm/gems/ruby-2.0.0-p648/gems/timeliness-0.4.4/lib/timeliness.rb:7:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/haider/.rvm/gems/ruby-2.0.0-p648/gems/ms_rest-0.6.4/lib/ms_rest.rb:8:in `<top (required)>'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/share/rvm/rubies/ruby-2.0.0-p648/bin/irb:12:in `<main>'
2.0.0-p648 :002 > 

```

**Comment by adzap** [comment]
Thanks.

Doing what you did above in Ruby 2.6.5 produces no error. I guess it is a Ruby compatibility issue but that's all I can say.

In the meantime I would peg timeliness to version 0.3.10 to avoid any issues.

**Comment by texpert** [comment]
Version 0.4.3 works OK with Ruby 2.2.0 - seems the change to squiggly heredoc is the culprit - it has been introduced only in Ruby 2.3

**Comment by adzap** [comment]
thanks @texpert, in that case I can wind back that change since it was of no consequence.

**Comment by texpert** [comment]
Yeah, that's be great, @adzap , even if the project I'm working at has already migrated to Ruby 2.3, I think there are still quite a bit projects using old rubies :)
